name: pixelatorial
version: 1.0.0
github: "aleperaltabazas/pixelatorial"
license: BSD3
author: "Alejandro Peralta Bazas"
maintainer: "aleperaltabazas@gmail.com"
copyright: "2021 Alejandro Peralta Bazas"

extra-source-files:
    - README.md
    - ChangeLog.md

# Metadata used when publishing your package
synopsis: An exhaustive image generator, pixelatorial can create any computable image (given enough time)
# category:            Web

description: Please see the README on GitHub at <https://github.com/aleperaltabazas/pixelatorial#readme>

dependencies:
    - base >= 4.7 && < 5
    - bytestring <= 0.10.10.1
    - directory <= 1.3.6.0
    - hspec
    - hedgehog == 1.0.3
    - optparse-applicative <= 0.15.1.0
    - time <= 1.12

library:
    source-dirs: src
    when:
        - condition: false
          other-modules: Paths_pixelatorial

executables:
    pixelatorial:
        main: Main.hs
        source-dirs: app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - pixelatorial
        when:
            - condition: false
              other-modules: Paths_pixelatorial

tests:
    pixelatorial-test:
        main: Spec.hs
        source-dirs: test
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - pixelatorial
